// Generated by srt_to_commentary_js.py from subtitles.srt
// Target structure: Array of commentary action objects

exports.commentary = [
  {
    timeSinceVideoStartedInMs: 62000,
    persistInHistory: false,
    action: {
      channel: 'game.commentary',
      data: {
        text: 'What\'s up everybody? It\'s Joe from Complex. We\'re in LA at Flight Club with the Grammy and Emmy award-winning Justin Timberlake.',
        timeCode: '01:02'
      }
    }
  },
  {
    timeSinceVideoStartedInMs: 70000,
    persistInHistory: false,
    action: {
      channel: 'game.commentary',
      data: {
        text: 'Going to do some sneaker shopping tonight, see what he\'s feeling, and hopefully buy some sneakers.',
        timeCode: '01:10'
      }
    }
  },
  {
    timeSinceVideoStartedInMs: 99000,
    persistInHistory: false,
    action: {
      channel: 'game.commentary',
      data: {
        text: 'Before we get to Jordan the shoes, I want to talk about Jordan the person. What was it like looking up to him?',
        timeCode: '01:39'
      }
    }
  },
  {
    timeSinceVideoStartedInMs: 110000,
    persistInHistory: false,
    action: {
      channel: 'game.commentary',
      data: {
        text: 'Gosh yeah, I had posters of MJ on my walls growing up in Tennessee.',
        timeCode: '01:50'
      }
    }
  },
  {
    timeSinceVideoStartedInMs: 123000,
    persistInHistory: false,
    action: {
      channel: 'game.commentary',
      data: {
        text: 'I started cutting grass on my street... 10 bucks a lawn... trying to save up to go wait in line at Foot Locker.',
        timeCode: '02:03'
      }
    }
  },
  {
    timeSinceVideoStartedInMs: 147000,
    persistInHistory: false,
    action: {
      channel: 'game.commentary',
      data: {
        text: 'I\'ll never forget when the black and Olive 9s came out. We all wanted those. Such an underrated pair.',
        timeCode: '02:27'
      }
    }
  },
  {
    timeSinceVideoStartedInMs: 192000,
    persistInHistory: false,
    action: {
      channel: 'game.commentary',
      data: {
        text: 'It\'s ironic that the two sneakers that had the most effect on me were the Jordan 3s and Air Max. Same guy, Tinker Hatfield.',
        timeCode: '03:12'
      }
    }
  },
  {
    timeSinceVideoStartedInMs: 264000,
    persistInHistory: false,
    action: {
      channel: 'game.commentary',
      data: {
        text: 'Where did I wear the Indiglo 14s? The \'Bye Bye Bye\' video. The whole crew matched.',
        timeCode: '04:24'
      }
    }
  },
  {
    timeSinceVideoStartedInMs: 373000,
    persistInHistory: false,
    action: {
      channel: 'game.commentary',
      data: {
        text: 'We want to talk Legends Of Summer. We did an all red one... the color of the shoe is the exact same color of the stage Jay and I built.',
        timeCode: '06:13'
      }
    }
  },
  {
    timeSinceVideoStartedInMs: 513000,
    persistInHistory: false,
    action: {
      channel: 'game.commentary',
      data: {
        text: 'We got to talk the Super Bowl moment. This pair is really special because it has the Nike Swoosh... Tinker\'s original sketch.',
        timeCode: '08:33'
      }
    }
  },
  {
    timeSinceVideoStartedInMs: 603000,
    persistInHistory: false,
    action: {
      channel: 'game.commentary',
      data: {
        text: 'Reggie from Jordan hits me and said the sneaker sold out in 5 minutes. I was like, wait, I was on stage for 12!',
        timeCode: '10:03'
      }
    }
  },
  {
    timeSinceVideoStartedInMs: 648000,
    persistInHistory: false,
    action: {
      channel: 'game.commentary',
      data: {
        text: 'My thing with the \'Man of the Woods\' shoe was I wanted it to feel like a boot.',
        timeCode: '10:48'
      }
    }
  },
  {
    timeSinceVideoStartedInMs: 700000,
    persistInHistory: false,
    action: {
      channel: 'game.commentary',
      data: {
        text: 'I had found this Sacai winter coat at Barney\'s... that coat inspired the shoe\'s color palette.',
        timeCode: '11:40'
      }
    }
  },
  {
    timeSinceVideoStartedInMs: 820000,
    persistInHistory: false,
    action: {
      channel: 'game.commentary',
      data: {
        text: 'The first pair of Jordans I ever had... there was a girl... she was the captain of our basketball team... she literally gave me the shoes off her feet.',
        timeCode: '13:40'
      }
    }
  },
  {
    timeSinceVideoStartedInMs: 1030000,
    persistInHistory: false,
    action: {
      channel: 'game.commentary',
      data: {
        text: 'So how can I help you out today? I\'m definitely going to get some stuff for me, but let\'s start with the kids first.',
        timeCode: '17:10'
      }
    }
  },
  {
    timeSinceVideoStartedInMs: 1070000,
    persistInHistory: false,
    action: {
      channel: 'game.commentary',
      data: {
        text: 'Okay, now to me. I got to do the Born and Raised. Oh, big dogs. Got to do those.',
        timeCode: '17:50'
      }
    }
  },
  {
    timeSinceVideoStartedInMs: 1076000,
    persistInHistory: false,
    action: {
      channel: 'game.commentary',
      data: {
        text: 'I think it\'s time to go to the big boy section. Let\'s do it.',
        timeCode: '17:56'
      }
    }
  },
  {
    timeSinceVideoStartedInMs: 1102000,
    persistInHistory: false,
    action: {
      channel: 'game.commentary',
      data: {
        text: 'You got the Red October? I do have the Octobers... All right, I\'ll take \'em.',
        timeCode: '18:22'
      }
    }
  },
  {
    timeSinceVideoStartedInMs: 1135000,
    persistInHistory: false,
    action: {
      channel: 'game.commentary',
      data: {
        text: 'Did I buy that many? I think so.',
        timeCode: '18:55'
      }
    }
  },
  {
    timeSinceVideoStartedInMs: 1143000,
    persistInHistory: false,
    action: {
      channel: 'game.commentary',
      data: {
        text: 'So your total tonight, we\'re looking at $22,014. Do I need to take out a loan?',
        timeCode: '19:03'
      }
    }
  },
  {
    timeSinceVideoStartedInMs: 1153000,
    persistInHistory: false,
    action: {
      channel: 'game.commentary',
      data: {
        text: 'You are all set my guy. Thank you so much. I got more than what I needed!',
        timeCode: '19:13'
      }
    }
  }
];
