// chat2.js generated by generate_chat2.js
exports.chat = [
    {
      "timeSinceVideoStartedInMs": 15000,
      "persistInHistory": false,
      "action": {
        "channel": "game.chat",
        "data": {
          "user": "bot-01",
          "text": "JT is a legend! Been waiting for this episode."
        }
      }
    },
    {
      "timeSinceVideoStartedInMs": 32000,
      "persistInHistory": false,
      "action": {
        "channel": "game.chat",
        "data": {
          "user": "bot-02",
          "text": "Flight Club LA is the spot."
        }
      }
    },
    {
      "timeSinceVideoStartedInMs": 65000,
      "persistInHistory": false,
      "action": {
        "channel": "game.chat",
        "data": {
          "user": "bot-03",
          "text": "That Super Bowl halftime show was iconic with those 3s."
        }
      }
    },
    {
      "timeSinceVideoStartedInMs": 95000,
      "persistInHistory": false,
      "action": {
        "channel": "game.chat",
        "data": {
          "user": "bot-04",
          "text": "The reflective swoosh is such a cool hidden detail."
        }
      }
    },
    {
      "timeSinceVideoStartedInMs": 125000,
      "persistInHistory": false,
      "action": {
        "channel": "game.chat",
        "data": {
          "user": "bot-05",
          "text": "Tinker Hatfield is the GOAT."
        }
      }
    },
    {
      "timeSinceVideoStartedInMs": 145000,
      "persistInHistory": false,
      "action": {
        "channel": "game.chat",
        "data": {
          "user": "bot-06",
          "text": "Those Bio Beige 3s are super underrated."
        }
      }
    },
    {
      "timeSinceVideoStartedInMs": 160000,
      "persistInHistory": false,
      "action": {
        "channel": "game.chat",
        "data": {
          "user": "bot-07",
          "text": "Leather laces definitely give it that luxury vibe."
        }
      }
    },
    {
      "timeSinceVideoStartedInMs": 175000,
      "persistInHistory": false,
      "action": {
        "channel": "game.chat",
        "data": {
          "user": "bot-08",
          "text": "\"Higher grade suede\" you can tell just looking at it."
        }
      }
    },
    {
      "timeSinceVideoStartedInMs": 200000,
      "persistInHistory": false,
      "action": {
        "channel": "game.chat",
        "data": {
          "user": "bot-09",
          "text": "I still prefer the Jordan 3 without the Swoosh, tbh."
        }
      }
    },
    {
      "timeSinceVideoStartedInMs": 215000,
      "persistInHistory": false,
      "action": {
        "channel": "game.chat",
        "data": {
          "user": "bot-10",
          "text": "No way, the Swoosh makes it look like a prototype. It's fire."
        }
      }
    },
    {
      "timeSinceVideoStartedInMs": 260000,
      "persistInHistory": false,
      "action": {
        "channel": "game.chat",
        "data": {
          "user": "bot-11",
          "text": "He really knows his history with Tinker."
        }
      }
    },
    {
      "timeSinceVideoStartedInMs": 290000,
      "persistInHistory": false,
      "action": {
        "channel": "game.chat",
        "data": {
          "user": "bot-12",
          "text": "The Legends of the Summer collection is worth a fortune now."
        }
      }
    },
    {
      "timeSinceVideoStartedInMs": 310000,
      "persistInHistory": false,
      "action": {
        "channel": "game.chat",
        "data": {
          "user": "bot-13",
          "text": "Imagine finding a pair of those red Jordans at a scavenger hunt..."
        }
      }
    },
    {
      "timeSinceVideoStartedInMs": 335000,
      "persistInHistory": false,
      "action": {
        "channel": "game.chat",
        "data": {
          "user": "bot-14",
          "text": "Those scavenger hunts were crazy times on Twitter."
        }
      }
    },
    {
      "timeSinceVideoStartedInMs": 390000,
      "persistInHistory": false,
      "action": {
        "channel": "game.chat",
        "data": {
          "user": "bot-15",
          "text": "The Atmos Air Max 1s! My grails."
        }
      }
    },
    {
      "timeSinceVideoStartedInMs": 405000,
      "persistInHistory": false,
      "action": {
        "channel": "game.chat",
        "data": {
          "user": "bot-16",
          "text": "Elephant print on an Air Max just works so well."
        }
      }
    },
    {
      "timeSinceVideoStartedInMs": 425000,
      "persistInHistory": false,
      "action": {
        "channel": "game.chat",
        "data": {
          "user": "bot-17",
          "text": "He's right, the Jordan 3 is the perfect silhouette."
        }
      }
    },
    {
      "timeSinceVideoStartedInMs": 480000,
      "persistInHistory": false,
      "action": {
        "channel": "game.chat",
        "data": {
          "user": "bot-18",
          "text": "Those Mike Jordan stories are hilarious."
        }
      }
    },
    {
      "timeSinceVideoStartedInMs": 550000,
      "persistInHistory": false,
      "action": {
        "channel": "game.chat",
        "data": {
          "user": "bot-19",
          "text": "The Seoul 3s are so clean with the flag colors."
        }
      }
    },
    {
      "timeSinceVideoStartedInMs": 610000,
      "persistInHistory": false,
      "action": {
        "channel": "game.chat",
        "data": {
          "user": "bot-20",
          "text": "Virgil changed everything with the deconstructed look."
        }
      }
    },
    {
      "timeSinceVideoStartedInMs": 625000,
      "persistInHistory": false,
      "action": {
        "channel": "game.chat",
        "data": {
          "user": "bot-21",
          "text": "UNC Off-Whites are probably the best of the ten."
        }
      }
    },
    {
      "timeSinceVideoStartedInMs": 650000,
      "persistInHistory": false,
      "action": {
        "channel": "game.chat",
        "data": {
          "user": "bot-22",
          "text": "I love how he appreciates the craftsmanship."
        }
      }
    },
    {
      "timeSinceVideoStartedInMs": 720000,
      "persistInHistory": false,
      "action": {
        "channel": "game.chat",
        "data": {
          "user": "bot-23",
          "text": "Fear of God 1s... looked like spaceships when they came out."
        }
      }
    },
    {
      "timeSinceVideoStartedInMs": 750000,
      "persistInHistory": false,
      "action": {
        "channel": "game.chat",
        "data": {
          "user": "bot-24",
          "text": "Jerry Lorenzo really bridged performance and luxury."
        }
      }
    },
    {
      "timeSinceVideoStartedInMs": 850000,
      "persistInHistory": false,
      "action": {
        "channel": "game.chat",
        "data": {
          "user": "bot-25",
          "text": "LeBron Watch was such a cool program."
        }
      }
    },
    {
      "timeSinceVideoStartedInMs": 880000,
      "persistInHistory": false,
      "action": {
        "channel": "game.chat",
        "data": {
          "user": "bot-26",
          "text": "The Diamond Turf strap on the LeBron 15 is crazy."
        }
      }
    },
    {
      "timeSinceVideoStartedInMs": 920000,
      "persistInHistory": false,
      "action": {
        "channel": "game.chat",
        "data": {
          "user": "bot-27",
          "text": "He's grabbing everything off the shelf!"
        }
      }
    },
    {
      "timeSinceVideoStartedInMs": 950000,
      "persistInHistory": false,
      "action": {
        "channel": "game.chat",
        "data": {
          "user": "bot-28",
          "text": "Wait... did he just spot them?"
        }
      }
    },
    {
      "timeSinceVideoStartedInMs": 965000,
      "persistInHistory": false,
      "action": {
        "channel": "game.chat",
        "data": {
          "user": "bot-29",
          "text": "RED OCTOBERS."
        }
      }
    },
    {
      "timeSinceVideoStartedInMs": 980000,
      "persistInHistory": false,
      "action": {
        "channel": "game.chat",
        "data": {
          "user": "bot-30",
          "text": "The holy grail."
        }
      }
    },
    {
      "timeSinceVideoStartedInMs": 1000000,
      "persistInHistory": false,
      "action": {
        "channel": "game.chat",
        "data": {
          "user": "bot-31",
          "text": "Those are easily $15k+ right now."
        }
      }
    },
    {
      "timeSinceVideoStartedInMs": 1020000,
      "persistInHistory": false,
      "action": {
        "channel": "game.chat",
        "data": {
          "user": "bot-32",
          "text": "\"Do I need to take out a loan?\" LMAO 😂"
        }
      }
    },
    {
      "timeSinceVideoStartedInMs": 1050000,
      "persistInHistory": false,
      "action": {
        "channel": "game.chat",
        "data": {
          "user": "bot-33",
          "text": "He's actually doing it. He's buying the Yeezy 2s."
        }
      }
    },
    {
      "timeSinceVideoStartedInMs": 1080000,
      "persistInHistory": false,
      "action": {
        "channel": "game.chat",
        "data": {
          "user": "bot-34",
          "text": "The gold aglets on those are iconic."
        }
      }
    },
    {
      "timeSinceVideoStartedInMs": 1120000,
      "persistInHistory": false,
      "action": {
        "channel": "game.chat",
        "data": {
          "user": "bot-35",
          "text": "Checking out..."
        }
      }
    },
    {
      "timeSinceVideoStartedInMs": 1130000,
      "persistInHistory": false,
      "action": {
        "channel": "game.chat",
        "data": {
          "user": "bot-36",
          "text": "That total is going to be astronomical."
        }
      }
    },
    {
      "timeSinceVideoStartedInMs": 1140000,
      "persistInHistory": false,
      "action": {
        "channel": "game.chat",
        "data": {
          "user": "bot-37",
          "text": "$22,000!!! 💀"
        }
      }
    },
    {
      "timeSinceVideoStartedInMs": 1150000,
      "persistInHistory": false,
      "action": {
        "channel": "game.chat",
        "data": {
          "user": "bot-38",
          "text": "Dropped 20 bands like it was nothing."
        }
      }
    },
    {
      "timeSinceVideoStartedInMs": 1160000,
      "persistInHistory": false,
      "action": {
        "channel": "game.chat",
        "data": {
          "user": "bot-39",
          "text": "Great episode. JT has taste."
        }
      }
    },
    {
      "timeSinceVideoStartedInMs": 1165000,
      "persistInHistory": false,
      "action": {
        "channel": "game.chat",
        "data": {
          "user": "bot-40",
          "text": "Joe La Puma is the best host."
        }
      }
    }
  ];